Music.App/Models/Key.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Music.App.Models
{
    public class Key
    {
        public int Id { get; set; }
        public string KeyValue { get; set; }
    }
}

Music.App/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Music.BLL;

namespace Music.App.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.DateTimeNow = DateTime.Now;
            ViewBag.Message = "This is the about page!";

            return View();
        }

        //public ActionResult Contact()
        //{
        //    ViewBag.Message = "Please email all inquires to:";

        //    return View();
        //}
    }
}

Music.App/Controllers/KeySignaturesController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Music.BLL;
using Music.App.Models;


namespace Music.App.Controllers
{
    public class KeySignaturesController : Controller
    {
        // GET: KeySignatures
        public ActionResult Index()
        {
            ViewBag.KeyColor = "";
            return View();
        }

        [HttpPost]
        public ActionResult Index(KeySignatureForm keySignature)
        {
            // passing form variables to calculate key signature
            CalculateKeySignature(keySignature.Key, keySignature.Accidential, keySignature.Mode, keySignature.CustomMode);

            return View();
        }

        // method to calculate the key signature and display
        public void CalculateKeySignature(char key, string accidential, string mode, string customMode)
        {

            // pass input values from form to ModeResponse method in the BLL, assign results to string
            string[] modeResult = KeySigGenerator.ModeResponse(key, accidential, mode, customMode);

            ViewBag.Result = String.Format("The keys are: {0} {1} {2} {3} {4} {5} {6} {7}", modeResult[0], modeResult[1], modeResult[2], modeResult[3], modeResult[4], modeResult[5], modeResult[6], modeResult[7]);

            for (int i = 0; i < 7; i++)
            {
                switch (modeResult[i])
                {
                    case "C":
                        ViewBag.KeyColorC = "white-selected";
                        break;
                    case "D♭":
                        ViewBag.KeyColorCS = "black-selected";
                        break;
                    case "D":
                        ViewBag.KeyColorD = "white-selected";
                        break;
                    case "E♭":
                        ViewBag.KeyColorDS = "black-selected";
                        break;
                    case "E":
                        ViewBag.KeyColorE = "white-selected";
                        break;
                    case "F":
                        ViewBag.KeyColorF = "white-selected";
                        break;
                    case "G♭":
                        ViewBag.KeyColorFS = "black-selected";
                        break;
                    case "G":
                        ViewBag.KeyColorG = "white-selected";
                        break;
                    case "A♭":
                        ViewBag.KeyColorGS = "black-selected";
                        break;
                    case "A":
                        ViewBag.KeyColorA = "white-selected";
                        break;
                    case "B♭":
                        ViewBag.KeyColorAS = "black-selected";
                        break;
                    case "B":
                        ViewBag.KeyColorB = "white-selected";
                        break;
                    default:
                        ViewBag.KeyColorError = "The key color broke!";
                        break;
                }
            }
        }

    }
}

Music.App/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>


<p>The time now is @ViewBag.DateTimeNow</p>

Music.App/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title</h2>
<h4>@ViewBag.Message</h4>

<address>
    <strong>Email:</strong>   <a href="mailto:tyler.hooper258@gmail.com">Tyler.Hooper258@gmail.com</a>
</address>

Music.App/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<header>
    <div class="keysig-text-box">
        <h1>Get started<br />writing great music.</h1>
        <a class="btn-main btn-full" href="#">Show me how</a>
    </div>
</header>

<section class="section-keysig">
    <div class="row">
        <h2>Your music needs all in one place</h2>
        <p class="long-copy">
            Knowing where to start when writing a song can be challenging. Don't worry, your Music Companion is here to help! Whether you're struggling to start, or in need of inspiration to spice up your composition, you'll find a variety of tools here to assist you.
        </p>
    </div>

    <div class="row center-block">
        <div class="col-md-4">
            <ion-icon name="musical-note" class="category-icon"></ion-icon>
            <h3>Key Signatures</h3>
            <p class="desc">
                Great songs start with the right key signature. This tool will help you pick where to start with writing your musical composition.
            </p>
            <p>
                @Html.ActionLink("Go Now", "Index", "KeySignatures", null, new { @class = "btn-main btn-full" }) 
            </p>

        </div>
        <div class="col-md-4">
            <ion-icon name="musical-notes" class="category-icon"></ion-icon>
            <h3>Chords</h3>
            <p class="desc">
                Need to find just the right chord? This tool will help you find the one you are looking for. Simply select your key signature, and we'll do the rest.
            </p>
            <p>
                <a class="btn-main btn-ghost" href="#">Coming Soon...</a>
            </p>
        </div>
        <div class="col-md-4">
            <ion-icon name="headset" class="category-icon"></ion-icon>
            <h3>Chord Progressions</h3>
            <p class="desc">
                A good chord progression is the bread and butter of a great composition. Use this tool to help you get started with capturing the feel you are looking for.
            </p>
            <p>
                <a class="btn-main btn-ghost" href='#'>Coming Soon...</a>
            </p>
        </div>
    </div>
</section>

Music.App/Views/KeySignatures/Index.cshtml
@{
    ViewBag.Title = "Key Signatures";
}

@using (Html.BeginForm("Index", "KeySignatures", FormMethod.Post))
{
    <section class="key-sig-form">
        <div class="row center-block">
            <div class="format-form">
                <form class="form-horizontal">
                    <div class="form-inline">
                        <div class="col-md-3 form-column">
                            <div class="col-md-6 form-column">
                                <select id="Key" name="Key" class="form-control form-element">
                                    <option value='C'>C</option>
                                    <option value='D'>D</option>
                                    <option value='E'>E</option>
                                    <option value='F'>F</option>
                                    <option value='G'>G</option>
                                    <option value='A'>A</option>
                                    <option value='B'>B</option>
                                </select>
                            </div>

                            <div class="col-md-6 form-column">
                                <select id="Accidential" name="Accidential" class="form-control form-element">
                                    <option value="natural">♮</option>
                                    <option value="flat">♭</option>
                                    <option value="sharp">#</option>
                                </select>
                            </div>
                        </div>

                        <div class="col-md-3 form-column">
                            <select id="Mode" name="Mode" class="form-control form-element">
                                <option value="major">Major</option>
                                <option value="natMinor">Natural Minor</option>
                                <option value="harMinor">Harmonic Minor</option>
                                <option value="melMinor">Melodic Minor</option>
                                <option value="dorian">Dorian</option>
                                <option value="phrygian">Phrygian</option>
                                <option value="lydian">Lydian</option>
                                <option value="mixolydian">Mixolydian</option>
                                <option value="locrian">Locrian</option>
                                <option value="other">Other...</option>
                            </select>
                        </div>

                        <div class="col-md-3 form-column">
                            @*<input id="CustomMode" name="CustomMode" type="text" class="form-control form-element" placeholder="Custom" disabled>*@
                        </div>

                        <div class="col-md-3 form-column">
                            <button type="submit" id="submit" class="btn btn-default form-element">Submit</button>
                        </div>
                    </div>
</form>
            </div>
        </div>
    </section>

    //KEYBOARD

    <div class="container-fluid">
        <div class="row">
            <ul class="set format-keys center-block">
                <li id="cKey" name="cKey" class="white @ViewBag.KeyColorC c"></li>
                <li id="csKey" name="csKey" class="black @ViewBag.KeyColorCS cs"></li>
                <li id="dKey" name="dKey" class="white @ViewBag.KeyColorD d"></li>
                <li id="dsKey" name="dsKey" class="black @ViewBag.KeyColorDS ds"></li>
                <li id="eKey" name="eKey" class="white @ViewBag.KeyColorE e"></li>
                <li id="fKey" name="fKey" class="white @ViewBag.KeyColorF f"></li>
                <li id="fsKey" name="fsKey" class="black @ViewBag.KeyColorFS fs"></li>
                <li id="gKey" name="gKey" class="white @ViewBag.KeyColorG g"></li>
                <li id="gsKey" name="gsKey" class="black @ViewBag.KeyColorGS gs"></li>
                <li id="aKey" name="aKey" class="white @ViewBag.KeyColorA a"></li>
                <li id="asKey" name="asKey" class="black @ViewBag.KeyColorAS as"></li>
                <li id="bKey" name="bKey" class="white @ViewBag.KeyColorB b"></li>
                <li id="cKey" name="cKey" class="white @ViewBag.KeyColorC c"></li>
                <li id="csKey" name="csKey" class="black @ViewBag.KeyColorCS cs"></li>
                <li id="dKey" name="dKey" class="white @ViewBag.KeyColorD d"></li>
                <li id="dsKey" name="dsKey" class="black @ViewBag.KeyColorDS ds"></li>
                <li id="eKey" name="eKey" class="white @ViewBag.KeyColorE e"></li>
                <li id="fKey" name="fKey" class="white @ViewBag.KeyColorF f"></li>
                <li id="fsKey" name="fsKey" class="black @ViewBag.KeyColorFS fs"></li>
                <li id="gKey" name="gKey" class="white @ViewBag.KeyColorG g"></li>
                <li id="gsKey" name="gsKey" class="black @ViewBag.KeyColorGS gs"></li>
                <li id="aKey" name="aKey" class="white @ViewBag.KeyColorA a"></li>
                <li id="asKey" name="asKey" class="black @ViewBag.KeyColorAS as"></li>
                <li id="bKey" name="bKey" class="white @ViewBag.KeyColorB b"></li>
            </ul>
        </div>
    </div>

    <br/>
    @ViewBag.Result
    @ViewBag.KeyColorError
}

Music.App/Views/KeySignatures/Result.cshtml
@{
    ViewBag.Title = "Result";
}

<h2>@ViewBag.Title</h2>
<h5>@ViewBag.Message</h5>

<div>
    <ul class="set">
        <li class="white b" style="background-color:#4cff00"></li>
        <li class="black as"></li>
        <li class="white a"></li>
        <li class="black gs"></li>
        <li class="white g"></li>
        <li class="black fs"></li>
        <li class="white f"></li>
        <li class="white e"></li>
        <li class="black ds"></li>
        <li class="white d"></li>
        <li class="black cs"></li>
        <li class="white c"></li>
        <li class="white b"></li>
        <li class="black as"></li>
        <li class="white a"></li>
        <li class="black gs"></li>
        <li class="white g"></li>
        <li class="black fs"></li>
        <li class="white f"></li>
        <li class="white e"></li>
        <li class="black ds"></li>
        <li class="white d"></li>
        <li class="black cs"></li>
        <li class="white c"></li>
    </ul>
</div>

Music.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,300,300i,400&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="vendors/css/ionicons.min.css">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="https://unpkg.com/ionicons@4.5.10-0/dist/ionicons.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Music Companion", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Key Signatures", "Index", "KeySignatures")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container-fluid body-content center-block">
        @RenderBody()
        <hr />
        <footer>
            <p class="footer-text">&copy; @DateTime.Now.Year - Created by Tyler Hooper</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>